# Machine-specific quirks for this MacBookPro14,1 (13-inch Intel, 2017).
#
# Deliberately NOT hardware-configuration.nix. That file carries a
# "Do not modify! It was generated by nixos-generate-config and may be
# overwritten by future invocations" banner, and it is the one file this repo
# does not publish to my-dotfiles (it is regenerated per machine from the disk
# UUIDs). Anything hand-written that landed there would be silently lost the
# next time the generator ran.
#
# Nothing in this module is generic. Every entry is a workaround for a defect in
# this specific chassis. If this configuration is ever restored onto other
# hardware, delete the import from configuration.nix rather than trying to make
# the contents portable.

{ config, lib, pkgs, ... }:

let
  # One SPI device carries BOTH the internal keyboard and the trackpad:
  #   Apple SPI Keyboard  -> event5
  #   Apple SPI Touchpad  -> event6
  # So a rebind drops the internal keyboard too, for roughly three seconds.
  # That is unavoidable and is why the script below does everything in one shot
  # with no step that needs input part-way through.
  applespiDev = "spi-APP000D:00";

  applespiRebind = pkgs.writeShellScriptBin "applespi-rebind" ''
    set -u

    DRV=/sys/bus/spi/drivers/applespi
    DEV=${applespiDev}

    # No-op cleanly on hardware without an Apple SPI keyboard, so the unit does
    # not turn up in `systemctl --failed` if this module is ever imported
    # somewhere it does not belong.
    if [ ! -d "$DRV" ]; then
      echo "no applespi driver here; nothing to do"
      exit 0
    fi

    # The unbind can legitimately fail if the device is already unbound (a
    # previous run left it that way, or the driver never attached). That is not
    # fatal -- the bind below is what matters.
    if [ -e "$DRV/$DEV" ]; then
      echo "$DEV" > "$DRV/unbind" 2>/dev/null || true
      sleep 2
    fi

    echo "$DEV" > "$DRV/bind" 2>/dev/null || true
    sleep 1

    # Fallback: a full module reload. This also clears the cached
    # touchpad_dimensions module param, forcing re-detection from the device.
    if [ ! -e "$DRV/$DEV" ]; then
      echo "bind failed -- reloading applespi module"
      ${pkgs.kmod}/bin/modprobe -r applespi || true
      sleep 1
      ${pkgs.kmod}/bin/modprobe applespi || true
      sleep 1
    fi

    if [ -e "$DRV/$DEV" ]; then
      echo "applespi rebound OK"
      exit 0
    else
      echo "applespi NOT bound -- plug in a USB keyboard/mouse" >&2
      exit 1
    fi
  '';

  # --- Ambient-light-driven keyboard backlight ---

  # ACPI0008 ambient light sensor, driven by the acpi_als module and exposed
  # through the IIO subsystem. Verified live on this machine: the reading drops
  # when the sensor beside the FaceTime camera is covered, so it tracks real
  # light rather than reporting a stuck constant.
  alsPath = "/sys/bus/iio/devices/iio:device0/in_illuminance_input";

  # The LED that applespi registers. Same SPI device as the keyboard and
  # trackpad, which is why this node comes and goes -- see the loop below.
  ledPath = "/sys/class/leds/spi::kbd_backlight/brightness";

  # Screen-off inhibit. While this file exists the daemon holds the keyboard
  # dark no matter what the sensor says.
  #
  # A file rather than a signal or a socket because the two ends sit on
  # opposite sides of a privilege boundary: the daemon is a system service, and
  # the thing that knows whether the screen is on is swayidle, running in the
  # user session. A file in /run is the cheapest thing both can reach -- and
  # checking it costs a shell builtin per tick, which matters given how hard
  # the loop below works to avoid forking.
  #
  # /run specifically, so a crash cannot leave the flag set. Anywhere
  # persistent and an unlucky reboot would leave the keyboard dark with no
  # visible cause and nothing in the logs.
  alsInhibitDir = "/run/kbd-backlight";
  alsInhibit = "${alsInhibitDir}/inhibit";

  kbdBacklightInhibit = pkgs.writeShellScriptBin "kbd-backlight-inhibit" ''
    set -u

    FLAG=${alsInhibit}

    case "''${1:-}" in
      on)
        # The daemon polls for this, so a plain truncate-to-create is enough --
        # no need to write anything into it.
        : > "$FLAG" 2>/dev/null || {
          echo "cannot create $FLAG -- is kbd-backlight-als installed?" >&2
          exit 1
        }
        ;;
      off)
        rm -f "$FLAG"
        ;;
      *)
        echo "usage: kbd-backlight-inhibit on|off" >&2
        exit 2
        ;;
    esac
  '';

  # Polling cadence, in seconds. Two rates rather than one, because the cost
  # and the benefit of polling are not in the same place.
  #
  # Measured on this machine, per operation:
  #
  #   $(cat file)            2.5  ms   (2.2 ms of it CPU -- fork + exec)
  #   read -r v < file       0.025 ms  (shell builtin, no process)
  #   $(helper) subshell     0.4  ms
  #   reading the ALS        1.9  ms wall, 0.15 ms CPU (ACPI _ALI call)
  #
  # The lesson is that the sensor is the cheap part. The first version of this
  # script spent ~8 ms of CPU per tick on eight forks and 0.15 ms actually
  # reading the sensor -- so the obvious lever, polling less often, was aimed
  # at the wrong thing. The loop below uses shell builtins throughout and forks
  # exactly once per tick, for sleep, which is the only fork left.
  #
  # With the work per tick now trivial, the remaining cost is the wakeup
  # itself: every tick pulls the CPU out of a deep idle state. So poll quickly
  # only while there is something to do (ramping between bands) and back off
  # when the level has settled. Sitting still in a dark room costs one wakeup
  # every 8 seconds; walking into one still responds within 8.
  alsPollFast = 1;
  alsPollSlow = 8;

  # Bands, darkest ambient first. A band applies while the sensor reads below
  # its `lux` figure; `led` is the keyboard brightness (0-255) there.
  #
  # Calibration point: this room measured 148 lux with the lights on, so the
  # top band's cutoff has to sit well below that or the keyboard would burn at
  # full power all day for no benefit. Tune the numbers here, not in the
  # script -- they are the only part worth adjusting.
  kbdBands = [
    { lux =       5; led = 255; }   # near-total darkness
    { lux =      15; led = 190; }
    { lux =      40; led = 130; }
    { lux =      90; led =  70; }
    { lux = 1000000; led =   0; }   # lit room: off entirely
  ];

  kbdBacklightAls = pkgs.writeShellScriptBin "kbd-backlight-als" ''
    set -u

    ALS=${alsPath}
    LED=${ledPath}
    INHIBIT=${alsInhibit}
    POLL_FAST=${toString alsPollFast}
    POLL_SLOW=${toString alsPollSlow}

    BAND_LUX="${lib.concatMapStringsSep " " (b: toString b.lux) kbdBands}"
    BAND_LED="${lib.concatMapStringsSep " " (b: toString b.led) kbdBands}"
    NBANDS=${toString (builtins.length kbdBands)}

    # These helpers return through a variable rather than by echoing, so the
    # caller does not need $( ), which is a fork. Ugly next to `x=$(f)`, but it
    # is the difference between ~7 forks a tick and none.
    #
    # Index into a space-separated list without eval. $1 is 1-based.
    nth() {
      _i=$1; shift
      while [ "$_i" -gt 1 ]; do shift; _i=$((_i - 1)); done
      REPLY_N=$1
    }

    lux_of() { nth "$1" $BAND_LUX; }
    led_of() { nth "$1" $BAND_LED; }

    # Which band a raw reading falls into, ignoring hysteresis.
    band_of() {
      _b=1
      while [ "$_b" -lt "$NBANDS" ]; do
        lux_of "$_b"
        [ "$1" -lt "$REPLY_N" ] && break
        _b=$((_b + 1))
      done
      REPLY_B=$_b
    }

    # Start assuming a lit room. The first poll in the dark corrects it, and
    # starting from "off" means a boot in daylight never flashes the keyboard.
    cur=$NBANDS
    last_written=""
    override_band=""

    while :; do
      # The LED node is destroyed and recreated by applespi-rebind-resume on
      # every wake, so finding it missing is normal here and not an error worth
      # logging. Clearing last_written matters: the recreated node starts at 0,
      # which would otherwise look exactly like the user having turned it down
      # by hand and would wedge this loop in override forever.
      if [ ! -r "$ALS" ] || [ ! -e "$LED" ]; then
        last_written=""
        sleep "$POLL_SLOW"
        continue
      fi

      # Screen off: hold the keyboard dark whatever the sensor says. A lit
      # keyboard under a blank screen is the one combination that is never
      # wanted -- nobody is looking at it, and on this battery it is pure loss.
      #
      # Set by swayidle at the moment it powers the monitors down and cleared
      # when they come back; see services.swayidle in configuration.nix.
      if [ -e "$INHIBIT" ]; then
        held=""
        { read -r held < "$LED"; } 2>/dev/null || held=""
        if [ "$held" != "0" ]; then
          printf '0\n' > "$LED" 2>/dev/null || true
        fi
        last_written=0

        # Forget where we were. Two reasons: the screen coming back should ramp
        # up from off rather than snap to the old level, and a manual override
        # from before the screen blanked should not outlive it -- by the time
        # you are back, "I turned it down ten minutes ago" is not a preference
        # worth preserving.
        cur=$NBANDS
        override_band=""

        # Poll quickly here, despite the screen being off and this looking like
        # exactly the moment to idle. It bounds how long the keyboard stays
        # dark after you touch the trackpad, and the window is inherently
        # short: the 900s idle timer suspends the machine about nine minutes
        # after the monitors go down, so this cannot run long enough for the
        # extra wakeups to matter.
        sleep "$POLL_FAST"
        continue
      fi

      # `read < file` is a builtin plus a redirect -- no process. The braces and
      # 2>/dev/null cover the race where the node passes the check above and is
      # then torn down by a rebind before the read.
      lux=""
      { read -r lux < "$ALS"; } 2>/dev/null || lux=""
      case "$lux" in
        "" | *[!0-9]*) sleep "$POLL_SLOW"; continue ;;
      esac

      actual=""
      { read -r actual < "$LED"; } 2>/dev/null || actual=""

      band_of "$lux"
      want=$REPLY_B

      # Manual override. If the level moved since we last set it, F5/F6 (or
      # anything else) touched it. Stand down and leave the user's choice alone
      # until the ambient light changes band -- which is what macOS does, and
      # without it every manual adjustment would be undone within two seconds.
      #
      # The -z guard is load-bearing and was missing in the first version. While
      # an override is active we deliberately stop writing, so actual stays
      # different from last_written for as long as it lasts -- meaning this test
      # keeps firing and, without the guard, kept re-arming override_band to the
      # *current* band on every tick. The release check below then compared the
      # band against itself, was always equal, and the daemon stayed stood down
      # permanently: turn the lights on and the keyboard never switched off.
      # Caught in simulation, not on the machine.
      if [ -z "$override_band" ] && [ -n "$last_written" ] && [ "$actual" != "$last_written" ]; then
        override_band=$want
      fi
      if [ -n "$override_band" ]; then
        if [ "$want" = "$override_band" ]; then
          # Standing down by request. Nothing to do until the light moves, so
          # take the slow cadence.
          sleep "$POLL_SLOW"
          continue
        fi
        override_band=""
      fi

      # Move one band per poll, with a 25% dead zone either side of each
      # boundary. Both halves matter: one-band-at-a-time turns a change into a
      # visible ramp rather than a jump, and the dead zone stops a reading
      # sitting on a boundary from oscillating between two levels forever.
      if [ "$want" -gt "$cur" ]; then
        # Brighter room, dim the keyboard: need to be 25% past the boundary.
        lux_of "$cur"
        if [ $((lux * 4)) -ge $((REPLY_N * 5)) ]; then
          cur=$((cur + 1))
        fi
      elif [ "$want" -lt "$cur" ]; then
        # Darker room, brighten: need to be 20% below the boundary below us.
        lux_of $((cur - 1))
        if [ $((lux * 5)) -lt $((REPLY_N * 4)) ]; then
          cur=$((cur - 1))
        fi
      fi

      led_of "$cur"
      target=$REPLY_N
      if [ "$target" != "$actual" ]; then
        printf '%s\n' "$target" > "$LED" 2>/dev/null || true
      fi
      last_written=$target

      # Adaptive cadence, and the only remaining fork in the loop. Still
      # ramping means there is work queued for the next tick, so stay quick;
      # once cur has caught up with want the level is settled and there is
      # nothing to do but watch, so back off and let the CPU idle deeply.
      if [ "$cur" != "$want" ]; then
        sleep "$POLL_FAST"
      else
        sleep "$POLL_SLOW"
      fi
    done
  '';
in
{
  # Available as `sudo applespi-rebind` for the times it wedges without a
  # suspend having happened. Replaces the throwaway /tmp script.
  environment.systemPackages = [ applespiRebind kbdBacklightAls kbdBacklightInhibit ];

  # Handshake point between the root daemon and the user session. root:users
  # 0775 so swayidle, running as the logged-in user, can create and remove the
  # flag inside it without any of this needing sudo, a setuid binary or a
  # polkit rule. The directory is the permission boundary; the flag itself is
  # just a name.
  systemd.tmpfiles.rules = [
    "d ${alsInhibitDir} 0775 root users -"
  ];

  # --- Apple SPI trackpad: re-probe after resume ---
  #
  # Measured on this machine (kernel 6.18.48):
  #
  #   23:50:11  boot modeswitch          -> 3.5 min, ZERO errors
  #   23:53:42  suspend entry (s2idle)
  #   23:55:01  resume; the driver runs its own re-init and logs
  #             "modeswitch done."
  #   23:55:12  "Received corrupted packet" begins and NEVER stops:
  #             ~8000 packets over 24 min (512 logged, 7516 hidden by
  #             dev_warn_ratelimited) until a manual rebind at 00:19:07.
  #   00:19:07  full unbind/bind         -> ZERO errors after.
  #
  # The failure is NOT a transport problem. Across that whole window there were
  # zero "SPI transfer timed out", zero "Error reading from device", zero
  # "failed to transfer one message" and zero DMAR faults. The bytes arrive
  # fine. Every error is one of exactly two shapes:
  #
  #   invalid message length 2 - num-fingers 0, tp-len 48
  #   invalid message length 8 - num-fingers 0, tp-len 48
  #
  # tp-len 48 is hex, i.e. 72 bytes -- a full multitouch report. The driver
  # wants 72 bytes and gets 2 or 8: the trackpad is emitting short status/ack
  # packets because it never entered multitouch reporting mode. The driver logs
  # "modeswitch done." when it *sends* the mode-switch, not when the device
  # acknowledges it, so a trackpad that ignores the command on the way out of
  # s2idle looks successful in the log and then streams garbage forever.
  #
  # A full unbind/bind re-runs the probe-time init sequence, which does make the
  # mode switch stick. So this is not a workaround papering over an unknown
  # cause -- it is the correct remedy for "device is in the wrong mode".
  # Upstream has a matching open problem: "applespi: Re-enable SPI on resume",
  # https://github.com/cb22/macbook12-spi-driver/pull/2
  #
  # NOT the same bug as Debian #1103830, which also reports "Received corrupted
  # packet" on a MacBookPro14,1. That one has SPI transfer timeouts, -110 read
  # errors, DMAR faults and a garbage length field (expected 4294967286, i.e.
  # -10 read as unsigned). None of those appear here, so the intel_iommu=off
  # advice attached to that bug does not apply and must not be copied in.
  #
  # Ordering note: After= plus WantedBy= on suspend.target is the systemd idiom
  # for "run on the way back up". It fires immediately at resume, deliberately
  # before the user starts typing at swaylock -- a rebind part-way through a
  # password would eat keystrokes.
  systemd.services.applespi-rebind-resume = {
    description = "Re-probe the Apple SPI keyboard/trackpad after resume";
    documentation = [ "https://github.com/cb22/macbook12-spi-driver/pull/2" ];
    after = [ "suspend.target" "hibernate.target" "hybrid-sleep.target" ];
    wantedBy = [ "suspend.target" "hibernate.target" "hybrid-sleep.target" ];
    serviceConfig = {
      Type = "oneshot";
      ExecStart = "${applespiRebind}/bin/applespi-rebind";
    };
  };

  # --- Keyboard backlight follows the ambient light sensor ---
  #
  # macOS does this in its own daemon; Linux has no equivalent. The kernel
  # exposes both halves -- acpi_als on the sensor side, the LED class on the
  # other -- but nothing bridges them, and none of the LED triggers listed in
  # /sys/class/leds/spi::kbd_backlight/trigger is a light sensor (they are all
  # keyboard-lock states: capslock, numlock and so on).
  #
  # Chosen over clight and wluma, both of which are packaged. Both are built
  # around a lux-to-*screen*-brightness curve with the keyboard as a secondary
  # output, so adopting either would mean configuring around a feature that is
  # not wanted here. The deciding factor was the LED node disappearing on every
  # resume (see applespi-rebind-resume above): a daemon that opens that path
  # once at startup stops working after the first suspend and says nothing
  # about it. The loop below re-checks the node every poll instead.
  #
  # Reconsider clight if screen auto-brightness is ever wanted too -- two
  # features justify a daemon, one does not.
  #
  # Runs as a system service rather than a user one so it survives logout and
  # can write the LED directly, without depending on logind being willing to
  # proxy the write for whoever happens to be logged in.
  systemd.services.kbd-backlight-als = {
    description = "Drive the keyboard backlight from the ambient light sensor";
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "simple";
      ExecStart = "${kbdBacklightAls}/bin/kbd-backlight-als";
      # The loop is defensive about missing sysfs nodes, so a restart here
      # means something genuinely unexpected. Keep it alive anyway; a dead
      # keyboard light is a nuisance nobody would think to check for.
      Restart = "always";
      RestartSec = 5;
      # Polls a sysfs file every couple of seconds -- it should never compete
      # with anything the user is actually waiting on.
      Nice = 10;
      NoNewPrivileges = true;
      ProtectHome = true;
      PrivateNetwork = true;
      # Deliberately NOT ProtectKernelTunables or ProtectSystem=strict: both
      # remount /sys read-only, which is the one thing this service exists to
      # write to.
    };
  };

  # --- Keep the SPI controller out of runtime PM ---
  #
  # 0000:00:1e.3 is the Intel LPSS SPI controller (8086:9d2a, driver
  # intel-lpss) that the Apple keyboard/trackpad hangs off. It defaults to
  # power/control=auto, so it can runtime-suspend independently of system
  # sleep, which gives the device another way to end up out of sync with the
  # driver.
  #
  # Status: this started out as a speculative "removes a variable" rule and
  # turned out to be load-bearing. Measured suspend entry -> exit, same kernel,
  # same machine, on 2026-09-13:
  #
  #   00:38:14  power/control=auto   38.08s     <- config switched at 00:37:26,
  #   23:53:42  power/control=auto   78.83s        but an ACTION=="add" rule does
  #                                                not retrigger on devices that
  #                                                are already enumerated
  #   00:49:48  power/control=on      2.84s     <- after `udevadm trigger`
  #   00:51:03  power/control=on      2.83s
  #
  # A 13x improvement, with the changeover falling exactly where the rule first
  # took effect. Caveat worth keeping: the rebind service above also began
  # running in that same window, so cycles 3 and 4 entered suspend with a
  # healthy applespi while cycle 2 entered with a driver that had been emitting
  # corrupt packets for 24 minutes. Two samples either side cannot separate the
  # two causes. Both are kept.
  #
  # Consequence for re-applying this config: after `nixos-rebuild switch`, run
  #   udevadm control --reload && udevadm trigger --action=add --subsystem-match=pci
  # or reboot. Without that the rule silently does nothing until next boot,
  # which is exactly the trap that made cycle 2 look like a failed fix.
  services.udev.extraRules = ''
    ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x8086", ATTR{device}=="0x9d2a", ATTR{power/control}="on"
  '';
}
